---
title: "PS270 Final Project"
author: "Jane C. Olson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in looking at data analyzing what parties American voters tend to say they prefer in presidential elections as they come closer to the election. I am curious as to whether or not voters tend to favor a certain party in the beginning of the election cycle versus the period nearest to the election. I hope to see this through American presidential pre-election polls.

## Tentative Proposal

Does closure of polling places in the U.S. decrease participation in elections? In this study, I plan to examine voter turnout from 2012 to 2018 versus 2020, when many polling places closed due to COVID-19. I hypothesize that in areas where most polling places are closed there is a lesser amount of voter turnout than areas that have more open polling places. When more polling places are closed, I suspect that it is less likely for people to vote. When less polling places are closed, I suspect that it is more likely for people to vote. My sample is comprised of data on polling locations used in 30 states from 2012 to 2020. My unit of analysis is data on polling locations used in 30 states from one of the 2012 to 2020 elections (e.g., the 2018 general election). The explanatory variable of interest is whether a city has multiple options for polling locations for voter (has more than one polling location open) or if it does not have multiple options for voters (only has one polling locations open). The variable is coded =1 for multiple polling locations open and =0 for only one polling location open. My outcome variable is the count of voters who show up at a polling place for a general election. For instance, if the variable were coded =1342, it would mean that 1342 voters showed up to a polling place for that general election. This variable is measured from Pratheek Rebala's data set on U.S. polling places from 2012 to 2020. If I observe a greater amount of voters at a polling place in a city with multiple polling places open, this would provide support for my hypothesis. If, on the other hand, I observe a lesser amount of voters or the same amount at a polling place in a city with multiple polling places open, this would provide evidence against my hypothesis. When I run my regression of the count of voters at a polling place for a general election on the multiple polling locations variable, a positive, significant coefficient would indicate support for my hypothesis.

## Data Visualization

```{r}
library(tidyverse)
library(dplyr)
library(readr)

ppeg_pres_2024v1 <- read_csv("final-data/ppeg_pres_2024v1.csv")

ppeg_pres <- ppeg_pres_2024v1

ggplot(data = ppeg_pres,
       mapping = aes(x = electorate_lastround,
                     y = total_vote_lastround)) +
  geom_point() +
  labs(x = "Number of Eligible Voters",
       y = "Total Number of Votes Cast",
       title = "Number of Votes Cast by Eligible Voters")
```







